name: optic_tv
description: A premium, professional IPTV application built from scratch.
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Premium Media Playback
  media_kit: ^1.1.0
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  url_launcher: ^6.3.0
  animations: ^2.0.11
  rxdart: ^0.27.7
  collection: ^1.18.0

  # State Management & DI
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  # Firebase & Backend
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  firebase_database: ^12.3.0
  firebase_messaging: ^16.2.0
  flutter_local_notifications: ^18.0.1

  # Localization & RTL
  flutter_localizations:
    sdk: flutter
  intl: any

  # Networking & Parsing
  dio: ^5.4.3+1
  m3u_nullsafe: ^1.0.4
  socket_io_client: ^3.0.0

  # Settings & persistence
  shared_preferences: ^2.2.3
  path_provider: ^2.1.5
  file_picker: ^8.1.7

  # UI & UX
  share_plus: ^12.0.1
  google_fonts: ^8.0.2
  image_picker: ^1.1.2
  glassmorphism: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.1
  palette_generator: ^0.3.3+3
  lottie: ^3.2.0
  simple_pip_mode: ^1.1.0
  dio_cache_interceptor: ^3.5.0

  # Native TV Engine & Detection
  video_player: ^2.9.1
  device_info_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.13.1
  riverpod_generator: ^4.0.3
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/optic_logo.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/images/optic_logo.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/optic_logo.png
  fonts:
    - family: Rabar
      fonts:
        - asset: assets/fonts/Rabar_021.ttf
          weight: 400
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
          weight: 400
